tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "secondary-fixed-dim": "#ffb59e",
                "error": "#ffb4ab",
                "surface-container-low": "#1c1b1b",
                "primary": "#ffffff",
                "on-tertiary-fixed": "#0b1d29",
                "surface-container-high": "#2a2a2a",
                "secondary": "#ffb59e",
                "on-secondary-fixed": "#3a0b00",
                "on-tertiary-container": "#556774",
                "on-secondary": "#5e1700",
                "on-error-container": "#ffdad6",
                "tertiary-fixed-dim": "#b6c9d8",
                "on-primary-fixed-variant": "#3c4d00",
                "on-surface": "#e5e2e1",
                "surface-tint": "#abd600",
                "inverse-primary": "#506600",
                "primary-fixed": "#c3f400",
                "on-primary-container": "#556d00",
                "on-secondary-fixed-variant": "#852400",
                "on-tertiary-fixed-variant": "#374956",
                "primary-fixed-dim": "#abd600",
                "inverse-on-surface": "#313030",
                "surface": "#131313",
                "secondary-container": "#ff571a",
                "on-error": "#690005",
                "on-primary-fixed": "#161e00",
                "tertiary-fixed": "#d2e5f5",
                "on-background": "#e5e2e1",
                "surface-container": "#201f1f",
                "surface-container-lowest": "#0e0e0e",
                "tertiary": "#ffffff",
                "inverse-surface": "#e5e2e1",
                "secondary-fixed": "#ffdbd0",
                "on-surface-variant": "#c4c9ac",
                "primary-container": "#c3f400",
                "on-primary": "#283500",
                "surface-variant": "#353534",
                "on-tertiary": "#21323e",
                "surface-bright": "#393939",
                "tertiary-container": "#d2e5f5",
                "surface-container-highest": "#353534",
                "surface-dim": "#131313",
                "error-container": "#93000a",
                "on-secondary-container": "#521300",
                "outline-variant": "#444933",
                "outline": "#8e9379",
                "background": "#131313"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "16px",
                "unit": "4px",
                "section-gap": "80px",
                "margin-desktop": "48px",
                "gutter": "16px"
            },
            "fontFamily": {
                "headline-lg": ["Anton"],
                "body-lg": ["Hanken Grotesk"],
                "display-xl": ["Anton"],
                "label-mono": ["Space Mono"],
                "title-md": ["Hanken Grotesk"],
                "headline-lg-mobile": ["Anton"],
                "body-sm": ["Hanken Grotesk"]
            },
            "fontSize": {
                "headline-lg": ["48px", {"lineHeight": "48px", "letterSpacing": "0.02em", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "26px", "fontWeight": "400"}],
                "display-xl": ["84px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
                "label-mono": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
                "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "700"}],
                "headline-lg-mobile": ["36px", {"lineHeight": "36px", "fontWeight": "400"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
        },
    },
}
